### PR TITLE
Issue #27: added 2 nginx containers and Varnish load balancing

### PR DESCRIPTION
**Pull request by alexdicianu**

### CODE REVIEW

**Comment by alexdicianu** [comment]
@timani could you give this branch a spin before I merge it into master? docker-compose.yml now has a variable in Varnish based on which you can use either one web host or 2. This is done automatically by either choosing a single node VCL file or a multi node one (Varnish needs to know how many nodes for load balancing).

Eventually we'll split docker-compose.yml into 2 (or more) files based on wether you want a multi node setup or not. Right now in a single node setup web2 still gets spun up, but it's not receiving any traffic.

**Comment by timani** [comment]
@alexdicianu this is a great start! Autoscaling can be for later and +1 to splitting them out later too. At least this way we can see and test what variables need to be set or changed. 

I will give this a try if I get some time today but if not before the meeting tomorrow.

**Comment by alexdicianu** [comment]
@timani damn, this is becoming a big one. So the only thing you need to do now is: `./argos up multinode or ./argos up` - defaults to single node. That will actually take a docker-compose file from the 2 templates, create a default docker-compose.yml and initialize it. 

It's actually better that working with the -f option all the time and it also gives you the possibility of using docker-compose as you would normally use it if you don't want to use ./argos

You can run as many `./argos up multinode` or `./argos up singlenode`. The command will stop all containers and reinitialize your stack.

**Comment by timani** [comment]
This one is turning out to have some teeth. I'll give this a try over the weekend. I see the rename of of the nginx -> web too. I'll pull over the branch in a fork and test each case. 

Setup with docker-compose:
- [x] single node
- [x] multi node 

Setup with args:
- [x] single node
- [x] multi node

**Comment by alexdicianu** [comment]
Tested the cases above, added a site, deleted one. All seems to be working. Merging.

**Pull request merged**
